name: "Build and Push"

on:
  push:
    branches:
      - main  # only build on push to main
  pull_request:  # still build for all PRs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes

      # - name: Cache Nix Store
      #   primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix') }}
      #   restore-prefixes-first-match: nix-${{ runner.os }}-

      # - name: Setup Cachix
      #   uses: cachix/cachix-action@v14
      #   with:
      #     name: charon
      #     authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build flake output
        run: nix build --accept-flake-config

      - name: Check devShell
        run: nix develop --accept-flake-config --command echo OK
